### ISSUE TITLE
image property in exporter pods are editable

### ISSUE THREAD

**Issue by vprashar2929** [sustainable-computing-io/kepler-operator#199]
When Kepler Instance is created from Operator in the case of `oc edit pod kepler-exporter-xyz` anyone can change the image tag of kepler from `release-0.5.x` to `xyz`. 
The editing of pod's configuration such as `image:` should be blocked for the user.

**Comment by sthaha** [comment]
@vprashar2929 could you please confirm that the operator does not revert back the change? Daemonset Controller should have reverted it back since Kepler Operator is only responsible for creating the Daemonset and not the pods.

**Comment by vprashar2929** [comment]
@sthaha No operator doesn't revert the changes. The revert only happens when you do `oc edit daemonset kepler-exporter-ds`

**Comment by sthaha** [comment]
Could you please provide a bit more details about the edits made? Could you please attach the pods.yaml before and after edit?

**Comment by vprashar2929** [comment]
Should we address this in the dev-preview? Wdyt?

**Comment by sthaha** [comment]
I am going to close this issue since this behavioural change should be addressed at kubernetes daemonset controller level and isn't specific to any operator. Operators create Daemonset / Deployment, rest is left to the platform (Daemonset controller in our case) to handle.

I would look at it as something beyond the scope of operator.  Do you want to start a discussion on https://github.com/kubernetes/kubernetes/ ?
